### ISSUE TITLE
After update of onlyoffice nextcloud fails to open documents

### ISSUE THREAD

**Issue by jonaschl** [ONLYOFFICE/onlyoffice-owncloud#146]
Hi,

yesterday I updated the onlyoffice package on my debian machine and now when I try to open a document I getting an error:

"Failed to download document"

before there is a message the document could not be saved.
![bildschirmfoto von 2018-01-17 13-55-57](https://user-images.githubusercontent.com/12372012/35043809-49625400-fb8e-11e7-9dab-5813cfbea37c.png)

Is an error with the new version known?

All apps and other packages are up to date.

**Comment by alexanderonlyoffice** [comment]
Hello @jonaschl,

Could you please send us logs of the document server and also NextCloud logs to **support@onlyoffice.com**

**Comment by jonaschl** [comment]
Hi,
thanks for your answer.
I think I have found the problem ( It works) but it seems weird to me.

I use secrets key as described here:
https://api.onlyoffice.com/editors/signature/

After I rolled the version back and the error still happens, I (just for fun) reset the settings in the nextcloud app. After that it worked, but why. So I had a look at /etc/onlyoffice/documentserver/default.json
and encountered that the config was overridden in some way, my secrets are gone. When I had set the secrets again and reloaded everything the app was working.

So I see 2 errors here.
1. The apt-get upgrade process overrides the config files.
2. The error message should state the token is not correct.

Thanks for your effort

jonaschl

**Comment by alexanderonlyoffice** [comment]
Hello @jonaschl,

1) There should be a dialog window asking if you want to override the config or not while updating the document server. Please specify if there was such dialog window.

2) Specify also what version did you update the document server from? And the version you did the update to.

**Comment by pikaille** [comment]
I realized that I opened an issue that might be a duplicate. 
https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/169

**Comment by alexanderonlyoffice** [comment]
@jonaschl, please specify if the issue still exists. 

@pikaille, as far as we understood, the issue is resolved at the moment.

**Comment by CMobley7** [comment]
I get the same error as shown in the images above. The error in the out.log is

```
[2018-04-09 04:29:57.560] [ERROR] nodeJS - postData error: docId = 117_1523248193;url = http://nginx-server/index.php/apps/onlyoffice/track?doc=Rko4RGgxRkliSCtINk04a01Fc0RGc1NTMzJkVG14cDVyZkVmZzYwbWxXcz0/eyJmaWxlSWQiOjExNywib3duZXJJZCI6InJvb3QiLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ%3D%3D;data = {"key":"117_1523248193","status":1,"users":["root"],"actions":[{"type":1,"userid":"root"}]}
Error: Error response: statusCode:301 ;body:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.11</center>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:282:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
```
I'm using the https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud repo, with slight edits to the docker-compose file, which is included below, and the nginx.conf, which I edited slightly following 
https://www.linuxbabe.com/docker/onlyoffice-nextcloud-integration-docker. However, I use self-signed ssl certificates. Once I execute docker-compose up -d, I naviagate to /data/nextcloud/app_data/config/config.php and add the following line
```
'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  )
```
Afterward, I log into the nextcloud instance through the https interface. Once, it has finished its initial initialization, I log out and execute `sudo bash set_configuration.sh`. At this point, I log back in and create a document through the drop down and the above image occurs.

```
version: '3'

services:
  app:
    restart: always
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    networks:
      backend:
        ipv4_address: 192.168.10.10
    expose:
      - '80'
      - '9000'
    volumes:
      - /data/nextcloud/app_data:/var/www/html


  onlyoffice-document-server:
    restart: always
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    networks:
      backend:
        ipv4_address: 192.168.10.11
    expose:
      - '80'
      - '443'
    volumes:
      - /data/nextcloud/document_data:/var/www/onlyoffice/Data
      - /data/nextcloud/document_log:/var/log/onlyoffice


  nginx:
    restart: always
    container_name: nginx-server
    image: nginx:latest
    stdin_open: true
    tty: true
    networks:
      frontend:
        ipv4_address: 192.168.1.10
      backend:
        ipv4_address: 192.168.10.12
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /data/nextcloud/config/nginx.conf:/etc/nginx/nginx.conf
      - /data/nextcloud/config/ssl:/etc/nginx/ssl
      - /data/nextcloud/app_data:/var/www/html

volumes:
  mysql_data:


networks:
  frontend:
    external: true
  backend:
    external: true
```
