### ISSUE TITLE
Problem with Onlyoffice and Nextcloud

### ISSUE THREAD

**Issue by Gutz-Pilz** [ONLYOFFICE/onlyoffice-owncloud#16]
hey there. 
i've setup OnlyOffice as Docker Container. behind a reverseproxy (https)

thats the error message i get, when i try to open files.
![unbenannt2](https://cloud.githubusercontent.com/assets/3322071/23787379/0ad06d52-0572-11e7-896b-cb4151085262.PNG)

thats my automated proxy/https setup compose file 
```
version: '2'


services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/hannes/configs/.nginx/conf.d:/etc/nginx/conf.d
      - /home/hannes/configs/.nginx/vhost.d:/etc/nginx/vhost.d
      - /home/hannes/configs/.nginx/html:/usr/share/nginx/html
      - /home/hannes/configs/.nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/hannes/configs/.nginx/certs:/etc/nginx/certs:rw
    restart: always


  app:
    image: wonderfall/nextcloud
    container_name: nextcloud
    privileged: true
    links:
      - db
      - onlyoffice
      - redis
      - solr
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=20G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=Hannes
      - ADMIN_PASSWORD=supersecret
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecret
      - DB_HOST=db
      - VIRTUAL_HOST=cloud.domain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=cloud.domain.com
      - LETSENCRYPT_EMAIL=mail@domain.com
    volumes:
      - /media/Backup/Cloud/data:/data
      - /media/Backup/Cloud/config:/config
      - /media/Backup/Cloud/apps:/apps2
    networks:
      - proxy-tier
    restart: always

  db:
    image: mariadb
    container_name: db
    volumes:
      - /media/Backup/Cloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecret
    networks:
      - proxy-tier
    restart: always

  redis:
    image: redis
    container_name: redis
    networks:
      - proxy-tier
    restart: always

  solr:
    image: solr:6-alpine
    container_name: solr
    volumes:
      - /media/Backup/Cloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant
    networks:
      - proxy-tier
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    environment:
      - VIRTUAL_HOST=office.domain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=office.domain.com
      - LETSENCRYPT_EMAIL=mail@domain.com
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
