### ISSUE TITLE
The document could not be saved - ownCloud/server

### ISSUE THREAD

**Issue by IkumiMashiba** [ONLYOFFICE/onlyoffice-owncloud#234]
I am trying it locally. 
Somehow I failed to save. Is there a setting shortage. 
Please point out if there is a mistake. Thanks.

![onlydoc](https://user-images.githubusercontent.com/12806774/48592504-0dbd4080-e98c-11e8-889e-94342e4893d4.jpg)

## onlyoffice/documentserver error log
In the container:
/var/log/onlyoffice/documentserver/docservice/out.log
```
[ERROR] nodeJS - postData error: docId = 3551684200;url = http://owncloud:8080/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjMyLCJvd25lcklkIjoiYWRtaW4iLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.X9PEAntKd64EmEYRUDmhmuylX1pkZLwg843CPqnTYwo;data = {"key":"3551684200","status":1,"users":["admin"],"actions":[{"type":1,"userid":"admin"}]}
Error: Error response: statusCode:301 ;body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://owncloud:8080/owncloud/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaWxlSWQiOjMyLCJvd25lcklkIjoiYWRtaW4iLCJ0b2tlbiI6bnVsbCwiYWN0aW9uIjoidHJhY2sifQ.X9PEAntKd64EmEYRUDmhmuylX1pkZLwg843CPqnTYwo">here</a>.</p>
</body></html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```
### CentOS7.5 
 >Docker 18.06.1-ce
 docker-compose 1.23.1

### bridge network
```
docker network create my-network
```
### ownCloud/server (10.0.10)
 https://hub.docker.com/r/owncloud/server/
 docker-compose.yml add to
```
- OWNCLOUD_SUB_URL=/owncloud
- OWNCLOUD_LOG_TIMEZONE=Asia/Tokyo
```
### onlyoffice/documentserver
```
version: '3'

services:
  onlyoffice-documentserver:
    container_name: only
    image: onlyoffice/documentserver
    environment:
      TZ: JST-9
    networks:
      - my-network

networks:
    my-network:
      external: true
```

### nginx
- docker-compose.yml
SSL fake self signature.
```
version: '2'
services:
  nginx:
    container_name: nginx-px
    build:
      context: ./
      dockerfile: Dockerfile
    image: nginx-px
    volumes:
      - /var/www/html:/var/www
      - /var/log/nginx:/var/log/nginx
      - /root/docker/nginx/key:/etc/nginx/key
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: JST-9
    networks:
      - my-network
networks:
    my-network:
      external: true
```
- Dockerfile
```
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
```
- default.conf
```
server {
  listen      80;
  server_name 192.168.8.9;
  return 301 https://$host$request_uri;
}
server {
  listen      443 ssl;
  server_name own.huangru.local;
  server_tokens off;
  etag off;
  fastcgi_buffers 16 8k;
  access_log    /var/log/nginx/access.log;
  error_log     /var/log/nginx/error.log;
  ssl_protocols        TLSv1.2;
  ssl_certificate      /etc/nginx/key/server.crt;
  ssl_certificate_key  /etc/nginx/key/server.key;

  proxy_set_header X-Frame-Options SAMEORIGIN;
  proxy_set_header X-XSS-Protection "1; mode=block";
  proxy_set_header X-Content-Type-Options nosniff;
  add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';

  location /owncloud/ {
        proxy_set_header X-Forwarded-Proto   $scheme;
        proxy_set_header Host $server_name:$server_port;
        proxy_set_header X-Real-IP           $remote_addr;
        proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_pass       http://owncloud:8080;
  }
}
server {
  listen      443 ssl;
  server_name doc.huangru.local;
     :
**Same as above**
     :
  location / {
        proxy_set_header X-Forwarded-Proto   $scheme;
        proxy_set_header Host $server_name:$server_port;
        proxy_set_header X-Real-IP           $remote_addr;
        proxy_set_header X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_pass       http://only/;
  }
  ```
### ownCloud - ONLYOFFICE apps ver2.0.3 

- Result 
![onlydoc-2](https://user-images.githubusercontent.com/12806774/48592591-786e7c00-e98c-11e8-86b0-6e0fa02dd0bc.jpg)

- Document Editing Service address
```
https://doc.huangru.local/
```
- Document Editing Service address for internal requests from the server
Specify container name
```
http://only/
```
- Server address for internal requests from the Document Editing Service
Specify container name
```
http://owncloud:8080/
```
