### ISSUE TITLE
Document says it saved but it doesn't save

### ISSUE THREAD

**Issue by soneji** [ONLYOFFICE/onlyoffice-owncloud#318]
When I save a document it says document saved but there is no change written to disk. Below are my config files. I have looked in the nginx log and it is not showing anything.

I have also tried adding
```php
‘onlyoffice’ =>
array (
‘verify_peer_off’ => true,
),
```
and 
```php
‘allow_local_remote_servers’ => true,
```
to my nextcloud config file

These are my nextcloud settings
```yaml
Document Editing Service address: https://cloud.domain.com/
Secret key (leave blank to disable): ___
Advanced server settings
Document Editing Service address for internal requests from the server: http://onlyoffice-document-server/
Server address for internal requests from the Document Editing Service: https://cloud.domain.com/
```

```yaml
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 6066:80
    expose:
      - '80'
      - '443'
    volumes:
      - ./onlyoffice/document_data:/var/www/onlyoffice/Data
      - ./onlyoffice/document_log:/var/log/onlyoffice
  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 6065:80
    volumes:
      - ./webroot:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
```
My nginx conf for the onlyoffice site
```
map $http_host $this_host {
    "" $host;
    default $http_host;
}
map $http_x_forwarded_proto $the_scheme {
     default $http_x_forwarded_proto;
     "" $scheme;
}
map $http_x_forwarded_host $the_host {
    default $http_x_forwarded_host;
    "" $this_host;
}
map $http_upgrade $proxy_connection {
  default upgrade;
  "" close;
}
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Forwarded-Host $the_host;
proxy_set_header X-Forwarded-Proto $the_scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

server {
    
    server_name office.domain.com; 
    location / {
	proxy_pass http://localhost:6066/;
	proxy_http_version 1.1;
    }
    

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    client_max_body_size 10G;
    proxy_buffering off;

}
```
My nginx conf for my nextcloud site:
```
server {
    
    server_name cloud.domain.com;

    location / {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Host $host:$server_port;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_pass http://localhost:6065/;
    }
    

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    rewrite ^/.well-known/carddav$ https://cloud.domain.com/remote.php/dav redirect;

    rewrite ^/.well-known/caldav$ https://cloud.domain.com/remote.php/dav redirect;

    client_max_body_size 16400M;
    proxy_buffering off;
    add_header Strict-Transport-Security "max-age=15552000;" always;

}

server {
    if ($host = cloud.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name cloud.domain.com;

    listen 80;
    listen [::]:80;
    return 404; # managed by Certbot


}
```
